package io.politicalempathy;

/**
 * Interface used to provide methods based on success or completion of
 * of a task in Firebase Auth. This interface effectively listens to the
 *  result of a firebase auth task's onComplete() method call
 *  which is generated by the createUserWithEmailAndPassword() method
 *  call.
 */
public interface CompleteListener {

    /**
     * If the task returned from the complete method is successful
     * provide functionality based on the success.
     */
    void onSuccess();


    /**
     * If the task returned from the complete method fails
     * provide functionality based on the failure.
     */
    void onFailure();
}
